### ISSUE TITLE
How about authorization

### ISSUE THREAD

**Issue by alexandru-calinoiu** [JosephWoodward/graphiql-dotnet#10]
If my graphql endpoint requires authorization can I still use graphiql?

**Comment by junelau** [comment]
@alexandru-calinoiu If you are using cookie authentication, this line[https://github.com/JosephWoodward/graphiql-dotnet/blob/d5bc728c2318e740f50c756692bd332aeeee0ccf/src/graphiql/assets/index.html#L119] will do it for you. 

However, if you are using tokens, you'll need to save your token as a cookie - and include it as a header in your request.
``` javascript
function getCookie(name) {
  var re = new RegExp(name + "=([^;]+)");
  var value = re.exec(document.cookie);
  return value != null ? unescape(value[1]) : null;
}
```
and add the token to your request header
``` javascript
return fetch('/graphql', {
          method: 'post',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': "Bearer " + getCookie("access_token")
          }
}

```

**Comment by alexandru-calinoiu** [comment]
Got it, makes sens, thank you.

**Comment by MisterJimson** [comment]
I don't quite understand the second case, where do we modify the fetch code to include the auth header? In the client side code? We would need to maintain a fork to do this?

A small bit of UI that lets you set custom headers in the UI would be perfect and flexible for other cases as well.

**Comment by pain0486** [comment]
> @alexandru-calinoiu 
> 
> ```js
> function getCookie(name) {
>   var re = new RegExp(name + "=([^;]+)");
>   var value = re.exec(document.cookie);
>   return value != null ? unescape(value[1]) : null;
> }
> ```
> 
> and add the token to your request header
> 
> ```js
> return fetch('/graphql', {
>           method: 'post',
>           headers: {
>             'Accept': 'application/json',
>             'Content-Type': 'application/json',
>             'Authorization': "Bearer " + getCookie("access_token")
>           }
> }
> ```

Where would you add this? Speaking about the  Or is this something we would have to fork?

**Comment by josephwoodward** [comment]
@pain0486 You'd have to make the modification to the `index.html` file that's bundled with this library.

This definitely seems like something that would be good to build into this library so people don't have to modify the index file manually.

**Comment by pain0486** [comment]
@JosephWoodward Thanks... for the time being, I found an easy work around. I installed a Chrome extension called [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj)
Then I added the authorization header and my token and everything started working fine.
