### ISSUE TITLE
Nuget with latest

### ISSUE THREAD

**Issue by martingit** [JosephWoodward/graphiql-dotnet#11]
Hi,

Saw that you fixed the code to be compatible with netcoreapp2.0 but you havn't released it as nuget.
Could you please do so? :)

/Martin

**Comment by josephwoodward** [comment]
Oh crap, you're right! Sorry I completely forgot about that. I'll do it tonight when I get home - thanks for the reminder! 👍

**Comment by josephwoodward** [comment]
There we go, you should see an [update for this in NuGet](https://www.nuget.org/packages/graphiql/1.1.0). Thanks for making me aware of this.
