### ISSUE TITLE
Separate routs for GraphQL and GraphiQL

### ISSUE THREAD

**Issue by poulad** [JosephWoodward/graphiql-dotnet#16]
I'd like to configure two different routes for GraphQL such as `/api/graphql` and for GraphiQL such as `/graphiql` .

This currently is not possible.

**Comment by EmmanuelPonnudurai** [comment]
Can you not add the path explicitly? 
```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseGraphiQl("gaphiql");
    app.UseMvc();
}
```

**Comment by josephwoodward** [comment]
@pouladpld I'm doing some work around routes at the moment so I can add the option for separate routes.

**Comment by josephwoodward** [comment]
@poulad This has been added in the [latest release](https://www.nuget.org/packages/graphiql/1.2.0-beta-2) thanks to @FrankyBoy, I'll now close this issue. Feel free to reopen it if needed.
