### ISSUE TITLE
Docs sidebar not working

### ISSUE THREAD

**Issue by ravgupms** [JosephWoodward/graphiql-dotnet#17]
After integrating the nuget into my GraphQL server, when I launch GraphiQL, it make 2 POST calls to __schema and shows the schema result in the output window but when I opens the Doc pane, it says `No Schema Available`. 

![image](https://user-images.githubusercontent.com/32916246/36774090-7cb8cde0-1c11-11e8-806b-e0d3f916f410.png)

**Comment by josephwoodward** [comment]
I don't suppose you have a repo to reproduce this?

**Comment by ravgupms** [comment]
No.

Can you tell me what all can go wrong which can cause this problem or something which I can try on my end?

**Comment by ravgupms** [comment]
Got it working. 

I was sending the response as text/plain content type instead of application/json.

**Comment by josephwoodward** [comment]
Ooh nice, thanks for letting me know you've solved it and added what the problem was, hopefully might help others than run into this at some point.
