### ISSUE TITLE
Cannot find schema

### ISSUE THREAD

**Issue by tdekoekkoekod** [JosephWoodward/graphiql-dotnet#18]
I am unable to run any queries as it does not seem to be able to discover the schema.  I do have a GraphQL running on my /api/graphql and have included app.UseGraphiQl().  Are there any other things I need to do?

**Comment by josephwoodward** [comment]
Could you try run it on `/graphql` please?

**Comment by tdekoekkoekod** [comment]
thanks.  Its been a while since I posted that and not sure what I was doing at the time, but it is working now.

**Comment by josephwoodward** [comment]
Great, thanks for updating the issue, as someone maintaining this library it makes my life so much easier 👍

**Comment by sdykae** [comment]
The difference between the electron app is this error ;c
Thank you <3
