### ISSUE TITLE
Issue with installing the package

### ISSUE THREAD

**Issue by Malek94z** [JosephWoodward/graphiql-dotnet#2]
I am trying to install the package, but I need to know which .Net Framework version is supported.

**Comment by josephwoodward** [comment]
Hi @Malek94z, it's designed for .NET Core, targeting the .NET Standard 1.6 moniker. Which framework are you trying to use it with?

**Comment by josephwoodward** [comment]
Having not had a response, I'm going to close this. Please feel free to reply and I'll happily re-open it.
