### ISSUE TITLE
Missing schema intellisense 

### ISSUE THREAD

**Issue by DaveRocketmakers** [JosephWoodward/graphiql-dotnet#27]
Hi there. I'm having issues getting intellisense to appear with any of the released versions for this package.

When I access the graphiql site, it's making a successful request to obtain the json based graph ql schema. However, i'm not getting an intellisense when I start writing queries, nor do I get the document explorer populating. 

Is there something I'm missing?

My app start up looks like the following
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseGraphiQl("/graphql", "/api/graphql");

            app.UseMvc();
        }
```

where I have a post and get controller at the specified location.

**Comment by josephwoodward** [comment]
Hi, thanks for reporting this. Could you open your browser's dev tools and look for any JavaScript errors when trying to query from the GraphiQL UI?

**Comment by DaveRocketmakers** [comment]
I don't seem to be getting any Javascript errors. Tried on both Firefox and Chrome

**Comment by DaveRocketmakers** [comment]
Ignore this issue. My server implementation was not returning the result in a "data" field which is why it wasn't being picked up

**Comment by josephwoodward** [comment]
Oh cool, glad you found out why it wasn't working, thanks for updating :)
