### ISSUE TITLE
How to use with .net 4.7

### ISSUE THREAD

**Issue by RenatoPacheco** [JosephWoodward/graphiql-dotnet#35]
I searched a lot, but I didn't find how to use this package with .net 4.7 (not Core).
The documentation guides you to use IApplicationBuilder that does not exist in this framework.
Is there any place I can read how to do this setup?

Thanks

**Comment by josephwoodward** [comment]
I'm afraid isn't designed to work with .NET 4.7, it's a .NET Core only middleware.

**Comment by josephwoodward** [comment]
I'm going to close this awaiting your reply.
