### ISSUE TITLE
Autosuggestion and document explorer not working with .Net core 3.1.1 

### ISSUE THREAD

**Issue by DevendraRawat** [JosephWoodward/graphiql-dotnet#36]
I created a .net core 3.1.1. project and used graphiql.net. 

I noticed that autosuggestion and document explorer is not working with .Net core 3.1.1.  Although I am able to run queries via /graphql end point.

**Comment by josephwoodward** [comment]
Alright, I'll take a look. I need to update this to target 3.1 anyway, thanks for reporting it.

**Comment by josephwoodward** [comment]
Hi @DevendraRawat,

Which browser are you using? I've just tried this on 3.1 (the Demo app in this repo targets 3.1) and auto-complete appears to be working as expected:

![image](https://user-images.githubusercontent.com/1237341/75613869-53266280-5b2a-11ea-8a87-83eb939545eb.png)

**Comment by josephwoodward** [comment]
I'm going to close this awaiting your response then happy to open it again.
