### ISSUE TITLE
Question: Possible to pass Authorization Header?

### ISSUE THREAD

**Issue by ghost** [JosephWoodward/graphiql-dotnet#9]
My GraphQlController has an [Authorize] attribute applied to it, is there a way to send a header with
Authorize : bearer ... ?

Not much of an issue really, Just want to know if it's possible.

**Comment by josephwoodward** [comment]
Is your intention to only authorised users access to the GraphiQl endpoint?

**Comment by ghost** [comment]
Yes. I only want users to see their own data or data they are authorized to see.

Although I'm not sure if this is the best approach.
